---

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Include installation tasks
  include_tasks: "install.yml"
  tags: [mongodb]

- name: Include configure.yml
  include_tasks: configure.yml
  tags: [mongodb]

- name: Include configure-mongod.yml
  include_tasks: configure-mongod.yml
  when: mongod_enabled
  tags: [mongodb]

- name: Include security configuration
  include_tasks: security.yml
  when: ( mongod_config_final.security is defined
          and mongod_config_final.security.authorization == 'enabled' )

- name: Include MMS Agent configuration
  include_tasks: mms-agent.yml
  when: mongodb_mms_api_key != ""
  tags: [mongodb]

- name: Include configure-mongos.yml
  include_tasks: configure-mongos.yml
  when: mongos_enabled
  tags: [mongodb]