---

- name: mongod reload
  service: name={{ mongod_daemon_name }} state=reloaded
  when: mongodb_manage_service

- name: mongod restart
  service: name={{ mongod_daemon_name }} state=restarted
  when: mongodb_manage_service

- name: mongos reload
  service: name={{ mongos_daemon_name }} state=reloaded
  when: mongodb_manage_service

- name: mongos restart
  service: name={{ mongos_daemon_name }} state=restarted
  when: mongodb_manage_service

- name: mongodb-mms-automation-agent restart
  service: name=mongodb-mms-automation-agent state=restarted
  when: mongodb_manage_service

- name: reload systemd
  shell: systemctl daemon-reload
  when: mongodb_is_systemd and mongodb_manage_service

- name: restart sysfsutils
  service: name=sysfsutils state=restarted
